name: Checks

on:
  push:
  pull_request:

defaults:
  run:
    shell: bash

env:
  ACTIONS_RUNNER_DEBUG: true

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: '🔑 Checkout'
        uses: actions/checkout@v6

      - name: '🐰 Setup Bun'
        uses: oven-sh/setup-bun@main
        with:
          bun-version: latest

      - name: 'Install Dependencies'
        run: |
          bun install --frozen-lockfile
          cd example && bun install --frozen-lockfile

      - name: 'Format & Lint & Type Check'
        run: |
          bun --bun oxfmt --config oxfmt.config.ts . --check
          bun --bun oxlint \
            --config='oxlint.config.ts' \
            --type-check \
            --type-aware \
            --format='github'
          bun tsgo --project tsconfig.json --noEmit

      - name: 'Build'
        run: bun run build

      - name: 'Preview Release'
        run: bun x pkg-pr-new publish .
